apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  annotations:
  creationTimestamp: null
  generation: 1
  labels:
    app: cloud-influxdb
  name: cloud-influxdb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cloud-influxdb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cloud-influxdb
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: influxdb-creds
        image: docker.io/influxdb:1.7.7
        imagePullPolicy: IfNotPresent
        name: influxdb
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/influxdb
          subPath: influxdb
          name: var-lib-influxdb
        ports:
        - name: influxdb
          containerPort: 8086
          hostPort: 8086
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: var-lib-influxdb
        hostPath:
          path: /mnt/influxdb
      nodeSelector:
        name: k8s-node01
